name: CombatReforged
version: '0.1.1-ALPHA'
main: net.zetastore.combatreforged.Main
api-version: '1.21'
load: STARTUP
authors: [ GustavoZeta ]
description: A plugin about Combat
commands:
  flingme:
    description: "nothing"
  class:
    description: "nothing"